base_url = "https://anemone.pages.dev"
description = "A minimalist Zola theme that prioritizes clean CSS and avoids heavy JavaScript. Enjoy a seamless user experience with lightning-fast load times. Let your content take center stage in a clutter-free, elegant design that enhances readability. Responsive and efficient, anemone brings focus to your ideas."
compile_sass = false
minify_html = true
generate_feed = true

default_language = "en"

taxonomies = [
    {name = "tags", feed = true},
]

[languages.en]
weight = 1
title = "anemone"
languageName = "English"
languageCode = "en"
relativeURL = false

[languages.fr]
weight = 2
title = "anemone"
languageName = "Fran√ßais"
languageCode = "fr"
relativeURL = false

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Speyll"
display_author = true

favicon = "favicon.ico"
image = ""

default_theme = "dark"
list_pages = false
twitter_card = true

[[extra.header_nav]]
en = { name = "/home/", url = "/" }
fr = { name = "/accueil/", url = "/fr" }

[[extra.header_nav]]
en = { name = "/about/", url = "/about" }
fr = { name = "/concernant/", url = "/about" }

[[extra.header_nav]]
en = { name = "/journal/", url = "/journal" }
fr = { name = "/journal/", url = "/journal" }

[[extra.header_nav]]
en = { name = "/blog/", url = "/blog" }
fr = { name = "/blog/", url = "/blog" }
