base_url = "https://anemone.pages.dev"
description = "A minimalist Zola theme that prioritizes clean CSS and avoids heavy JavaScript. Enjoy a seamless user experience with lightning-fast load times. Let your content take center stage in a clutter-free, elegant design that enhances readability. Responsive and efficient, anemone brings focus to your ideas."
compile_sass = false
minify_html = true
generate_feed = true
default_language = "en"

taxonomies = [
    {name = "tags", feed = true},
]

[languages.fr]
weight = 2
languageName = "Fran√ßais"
languageCode = "fr"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Speyll"
display_author = true

favicon = "favicon.ico"
image = ""

default_theme = "light"
list_pages = false
twitter_card = true

header_nav = [
  { url = "/", name_en = "/home/", name_fr = "/accueil/" },
  { url = "/about", name_en = "/about/", name_fr = "/concernant/" },
  { url = "/journal", name_en = "/journal/", name_fr = "/journal/" },
  { url = "/blog", name_en = "/blog/", name_fr = "/blog/" }
]